brew cask install google-chrome
brew cask install spotify
brew cask install anaconda
brew cask install postman
brew cask install java8
brew cask install sourcetree
brew cask install android-studio
brew cask install android-sdk
brew cask install sketch
brew cask install skype	
brew cask install appcleaner
brew cask install vlc	
brew cask install proxyman
brew cask install docker
brew cask install battle-net
brew cask install steam
brew cask install cleanmymac
brew cask install rapidminer-studio