brew cask install visual-studio-code
code --install-extension dart-code.dart-code
code --install-extension dart-code.flutter
code --install-extension waderyan.gitblame
code --install-extension onjayamanne.git-extension-pack
code --install-extension donjayamanne.githistory
code --install-extension codezombiech.gitignor
code --install-extension eamodio.gitlens
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension vscjava.vscode-java-debug
code --install-extension editorconfig.editorconfig
code --install-extension vscode-anaconda-extension-pack
code --install-extension kevinkyang.auto-comment-blocks
code --install-extension steoates.autoimport
code --install-extension formulahendry.auto-close-tag
code --install-extension formulahendry.auto-rename-tag
code --install-extension nash.awesome-flutter-snippets
code --install-extension mgmcdermott.vscode-language-babel
code --install-extension aaron-bond.better-comments
code --install-extension coenraads.bracket-pair-colorizer
code --install-extension auchenberg.vscode-browser-preview
code --install-extension wmaurer.change-case
code --install-extension naumovs.color-highlight
code --install-extension bierner.color-info
code --install-extension equinusocio.vsc-community-material-theme
code --install-extension alexdima.copy-relative-path
code --install-extension pranaygp.vscode-css-peek
code --install-extension necinc.elmmet
code --install-extension baeumer.vscode-eslint
code --install-extension grapecity.gc-excelviewer
code --install-extension ms-vscode.go
code --install-extension ecmel.vscode-html-css
code --install-extension abusaidm.html-snippets
code --install-extension idleberg.icon-fonts
code --install-extension zignd.html-css-class-completion
code --install-extension eriklynd.json-tools
code --install-extension zhang.markdown-all-in-one
code --install-extension davidanson.vscode-markdownlint
code --install-extension pkief.material-icon-theme
code --install-extension equinusocio.vsc-material-theme
code --install-extension equinusocio.vsc-material-theme-icons
code --install-extension vscjava.vscode-maven
code --install-extension eg2.vscode-npm-script
code --install-extension christian-kohler.npm-intellisense
code --install-extension esbenp.prettier-vscode
code --install-extension eroen-meijer.pubspec-assist
code --install-extension ms-python.python
code --install-extension bung87.vscode-gemfile
code --install-extension jpoissonnier.vscode-styled-components
code --install-extension redhat.vscode-yaml
code --install-extension vscode-icons-team.vscode-icons
code --install-extension deerawan.vscode-faker
code --install-extension wingrunr21.vscode-ruby
code --install-extension visualstudioexptteam.vscodeintellicode
code --install-extension gruntfuggly.todo-tree
code --install-extension wayou.vscode-todo-highlight
code --install-extension tabnine.tabnine-vscode
code --install-extension shan.code-settings-sync
code --install-extension castwide.solargraph
code --install-extension rebornix.ruby
code --install-extension chrmarti.regex
code --install-extension msjsdiag.vscode-react-native
code --install-extension quicktype.quicktype